/*
 * API V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package at.c02.tempus.api.model;

import android.os.Parcel;
import android.os.Parcelable;

import com.google.gson.annotations.SerializedName;

import java.util.Date;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * Booking
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-08T22:14:53.361+02:00")
public class Booking implements Parcelable {
  @SerializedName("bookingId")
  private Integer bookingId = null;

  @SerializedName("projectId")
  private Integer projectId = null;

  @SerializedName("employeeId")
  private Integer employeeId = null;

  @SerializedName("beginDate")
  private Date beginDate = null;

  @SerializedName("endDate")
  private Date endDate = null;

  @SerializedName("completed")
  private Boolean completed = null;

  public Booking bookingId(Integer bookingId) {
    this.bookingId = bookingId;
    return this;
  }

   /**
   * Get bookingId
   * @return bookingId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getBookingId() {
    return bookingId;
  }

  public void setBookingId(Integer bookingId) {
    this.bookingId = bookingId;
  }

  public Booking projectId(Integer projectId) {
    this.projectId = projectId;
    return this;
  }

   /**
   * Get projectId
   * @return projectId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getProjectId() {
    return projectId;
  }

  public void setProjectId(Integer projectId) {
    this.projectId = projectId;
  }

  public Booking employeeId(Integer employeeId) {
    this.employeeId = employeeId;
    return this;
  }

   /**
   * Get employeeId
   * @return employeeId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getEmployeeId() {
    return employeeId;
  }

  public void setEmployeeId(Integer employeeId) {
    this.employeeId = employeeId;
  }

  public Booking beginDate(Date beginDate) {
    this.beginDate = beginDate;
    return this;
  }

   /**
   * Get beginDate
   * @return beginDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public Date getBeginDate() {
    return beginDate;
  }

  public void setBeginDate(Date beginDate) {
    this.beginDate = beginDate;
  }

  public Booking endDate(Date endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public Date getEndDate() {
    return endDate;
  }

  public void setEndDate(Date endDate) {
    this.endDate = endDate;
  }

  public Booking completed(Boolean completed) {
    this.completed = completed;
    return this;
  }

   /**
   * Get completed
   * @return completed
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getCompleted() {
    return completed;
  }

  public void setCompleted(Boolean completed) {
    this.completed = completed;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Booking booking = (Booking) o;
    return Objects.equals(this.bookingId, booking.bookingId) &&
        Objects.equals(this.projectId, booking.projectId) &&
        Objects.equals(this.employeeId, booking.employeeId) &&
        Objects.equals(this.beginDate, booking.beginDate) &&
        Objects.equals(this.endDate, booking.endDate) &&
        Objects.equals(this.completed, booking.completed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bookingId, projectId, employeeId, beginDate, endDate, completed);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Booking {\n");
    
    sb.append("    bookingId: ").append(toIndentedString(bookingId)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    employeeId: ").append(toIndentedString(employeeId)).append("\n");
    sb.append("    beginDate: ").append(toIndentedString(beginDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    completed: ").append(toIndentedString(completed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
  public void writeToParcel(Parcel out, int flags) {
     
    out.writeValue(bookingId);

    out.writeValue(projectId);

    out.writeValue(employeeId);

    out.writeValue(beginDate);

    out.writeValue(endDate);

    out.writeValue(completed);
  }

  public Booking() {
    super();
  }

  Booking(Parcel in) {
    
    bookingId = (Integer)in.readValue(null);
    projectId = (Integer)in.readValue(null);
    employeeId = (Integer)in.readValue(null);
    beginDate = (Date)in.readValue(null);
    endDate = (Date)in.readValue(null);
    completed = (Boolean)in.readValue(null);
  }
  
  public int describeContents() {
    return 0;
  }

  public static final Parcelable.Creator<Booking> CREATOR = new Parcelable.Creator<Booking>() {
    public Booking createFromParcel(Parcel in) {
      return new Booking(in);
    }
    public Booking[] newArray(int size) {
      return new Booking[size];
    }
  };
}

